spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:photobox
    driverClassName: org.h2.Driver
    username: sa
    password:
    name: h2DataSource
  h2:
    console:
      enabled: true
  batch:
    job:
      enabled: false
images:
  path: /home/dennis/projects/private/testfolder/

