---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dmacedo/java-node-alpine
    tag: 8u151-jdk-alpine3.7

inputs:
  - name: git-src

outputs:
  - name: artifact

run:
  user: root
  path: sh
  args:
    - -exc
    - |
      cd git-src
      ./gradlew clean build allTest --stacktrace
      mv build/libs/*.jar ../artifact/