---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: selenium/node-firefox
    tag: latest

inputs:
  - name: git-src

outputs:
  - name: artifact

run:
  path: sh
  args:
  - -exc
  - |
    cd git-src
    ./gradlew clean build allTest
    cp ./build/libs/*.jar ../artifact/webapp.jar