---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jhoglin/gradle-node
    tag: latest

inputs:
  - name: git-src

outputs:
  - name: artifact

run:
  user: root
  path: sh
  args:
  - -exc
  - |
    cd git-src
    ./gradlew clean build allTest --stacktrace
    cp ./build/libs/*.jar ../artifact/webapp.jar