---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dmacedo/java-node-alpine
    tag: 8u151-jdk-alpine3.7

inputs:
  - name: dev-src
  - name: version

outputs:
  - name: artifact

run:
  user: root
  path: sh
  args:
    - -exc
    - |
      cd dev-src
      ./gradlew clean build allTest --stacktrace
      version=$(head -n 1 ../version/version)
      cp ./build/libs/*.jar ../artifact/photobox-$version.jar
