---
platform: linux

image_resource:
  type: docker-image
  privileged: true
  source:
    repository: selenium/node-firefox
    tag: latest

inputs:
  - name: git-src

outputs:
  - name: artifact

run:
  path: sh
  args:
  - -exc
  - |
    export TERM=dumb
    cd git-src
    export GRADLE_USER_HOME=.gradle
    chmod 755 .gradle
    ./gradlew clean build allTest
    cp ./build/libs/*.jar ../artifact/webapp.jar