---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest

inputs:
  - name: develop-artifactory
  - name: version

outputs:
  - name: artifact

run:
  user: root
  path: sh
  args:
    - -exc
    - |
      cp ./develop-artifactory/*.jar ../artifact/
