---
resource_types:
  - name: artifactory
    type: docker-image
    source:
      repository: pivotalservices/artifactory-resource
  - name: discord-resource
    type: docker-image
    source:
      repository: trivigy/discord-resource
resources:
  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:dennispidun/photobox.git
      branch: version
      file: version
      private_key: ((git-private-key))
  - name: discord
    type: discord-resource
    check_every: 999999h
    source:
      token: ((discord-token))
  - name: develop-artifactory
    type: artifactory
    source:
      endpoint: http://51.75.71.87:8081/artifactory
      repository: "/java-develop/photobox"
      regex: "photobox-(?<version>.*).jar"
      username: ci
      password: ((artifactory-secret))
      skip_ssl_verification: true
  - name: git-src
    type: git
    source:
      uri: git@github.com:dennispidun/photobox.git
      branch: develop
      private_key: ((git-private-key))
jobs:
  - name: bump-major
    plan:
      - get: version
        params: { bump: major }
      - put: version
        params: { file: version/version }
  - name: bump-minor
    plan:
      - get: version
        params: { bump: minor }
      - put: version
        params: { file: version/version }
  - name: develop-build
    plan:
      - get: version
        trigger: true
        params: { bump: patch }
      - get: git-src
        trigger: false
      - task: build
        privileged: true
        file: git-src/ci/tasks/build-and-test.yml
        on_failure:
          put: discord
          params:
            channel: ((discord-channel-id))
            color: 16007746
            title: PhotoBox Build Status
            message: |
              Build failed!
      - put: develop-artifactory
        params: { file: artifact/photobox-*.jar }
        on_success:
          put: discord
          params:
            channel: ((discord-channel-id))
            color: 6076508
            title: PhotoBox Deployment Status
            message: |
              Successfully deployed to Artifactory
        on_failure:
          put: discord
          params:
            channel: ((discord-channel-id))
            color: 16007746
            title: PhotoBox Deployment Status
            message: |
              Deployment to Artifactory failed
      - put: version
        params: { file: version/version }