---
resource_types:
  - name: artifactory
    type: docker-image
    source:
      repository: pivotalservices/artifactory-resource
resources:
  - name: jfrog-artifactory
    type: artifactory
    source:
      endpoint: http://http://51.75.71.87:8081/artifactory
      repository: "/java-develop/photobox"
      username: ci
      password: ((artifactory-secret))
      skip_ssl_verification: true
  - name: git-src
    type: git
    source:
      uri: git@github.com:dennispidun/photobox.git
      branch: master
      private_key: ((git-private-key))
jobs:
  - name: build-and-test
    plan:
      - get: git-src
        trigger: true
      - task: build
        privileged: true
        file: git-src/ci/tasks/build-and-test.yml
      - put: jfrog-artifactory
        params: { file: artifact/photobox.jar }