---
resources:
- name: git-src
  type: git
  source:
    uri: git@github.com:dennispidun/photobox.git
    branch: master
    private_key: ((git-private-key))
jobs:
- name: build-and-test
  plan:
  - get: git-src
    trigger: true
  - task: build
    file: my-battleships-src/ci/tasks/build-and-test.yml